### ISSUE TITLE
Add context menu to screens

### ISSUE THREAD

**Issue by dfch** [dfch/biz.dfch.CS.Sunrise.DaaS.UI#1]
For some screens it is beneficial to have context menus enabled. We can use a library such as [nnn](http://sydcanem.com/bootstrap-contextmenu/) for this. However according to [this issue](https://github.com/sydcanem/bootstrap-contextmenu/issues/63), there is no support for touch screens.

On the other hand it is really easy to implement this as you can see in the [example](http://sydcanem.com/bootstrap-contextmenu/).

See also http://www.jqueryrain.com/demo/jquery-context-menu/

**Comment by rufer7** [comment]
will be implemented in dfensgmbh/biz.dfch.CS.Appclusive.UI
