### ISSUE TITLE
Improve view in Google Chrome & Mozilla FireFox

### ISSUE THREAD

**Issue by rufer7** [dfch/biz.dfch.CS.Sunrise.DaaS.UI#3]
![chrome](https://cloud.githubusercontent.com/assets/5937292/10424566/73938bfe-70d0-11e5-9ebc-651e8b088331.png)

**Comment by dfch** [comment]
fyi : this also applies to FireFox

**Comment by rufer7** [comment]
@dfch 
What the hell is FireFox? :hamster:

**Comment by rufer7** [comment]
will not be necessary anymore because the UI gets replaced with dfensgmbh/biz.dfch.CS.Appclusive.UI

**Comment by dfch** [comment]
so can we close the issue?

**Comment by rufer7** [comment]
If we go with the new UI what I would suppose to do, we can close this issue, yes
